import { AbstractImpl } from '../../abstract.impl';
import { CompanyConfigImpl } from '../company.config.impl';
import { CompanyConfig } from '../../../declaration';

export class MocksCompanyConfigs {
  webClockCompanyConfig: CompanyConfigImpl = AbstractImpl.fromJSON(
    {
      BlnCanAccessFeedback: true,
      BlnCanAccessOptions: true,
      BlnCanAccessRatesAndWages: true,
      BlnCanAccessShiftDifferential: true,
      BlnCanAddCompanyLocation: true,
      BlnCanComposeMessage: true,
      BlnCanResumeSession: false,
      BlnCanViewReleaseNotes: true,
      BlnCompTimeEnabled: true,
      BlnEnableExternalLogoutEmployeeURL: false,
      BlnEnableExternalLogoutUserURL: false,
      BlnEnableTrackedFields: true,
      BlnFirstTimeLogIn: false,
      BlnIgnoreCapitalTextTransformation: false,
      BlnJobCostingEnabled: false,
      BlnShouldExitOnMotion: true,
      BlnShowSystemWideSearch: true,
      BlnShowTutorial: false,
      BlnTimeIsHundredths: false,
      BlnUpdatePassword: false,
      BlnUseVirtualKeyboard: false,
      DatCurrentWeek: '2021-05-02',
      DblRateMaxValue: 99999.99,
      DblRateMinValue: 0,
      IntApplicationStartIn: 0,
      IntCompanyId: 500,
      IntDepartmentMaxLength: 100,
      IntLocationMaxLength: 30,
      IntManualPeriod: 18,
      IntRatePrecision: 2,
      IntScheduleGroupMaxLength: 30,
      IntSessionTimeoutMilliseconds: 300000,
      IntSessionTimeoutWarningMilliseconds: 30000,
      LngEmployeeIdMaxValue: 9999999999,
      LngEmployeeIdMinValue: 1,
      LngJobCodeIdMaxValue: 9999999999,
      LngJobCodeIdMinValue: 1,
      ObjAppConfig: {
        BlnEnableSameSiteSecureFlag: false,
        BlnIsWebClock: false,
        BlnShouldUseCookie: true,
        DatPersistentMax: '2078-12-31',
        DatPersistentMin: '1900-01-01',
        IntApplicationId: 30,
        IntCurrentWeekStaleException: 30,
        IntErrorExceptionValue: 5,
        IntExceptionTypeConfirmNegativeAccrualBalance: 101,
        IntExceptionTypeInvalidSession: 55,
        IntExceptionTypePersistence: 60,
        IntExceptionTypePresentation: 0,
        IntExceptionTypePresentationConfirmation: 20,
        IntExceptionTypePresentationConfirmationBioVerification: 24,
        IntExceptionTypePresentationConfirmationDeactivate: 21,
        IntExceptionTypePresentationConfirmationOfferExist: 26,
        IntExceptionTypePresentationConfirmationOfferTime: 27,
        IntExceptionTypePresentationConfirmationUnassign: 22,
        IntExceptionTypeUnableToReachServer: 100,
        IntExceptionTypeUnexpected: 99,
        IntExceptionTypeWorkflow: 70,
        IntFatalExceptionValue: 6,
        IntInformationExceptionValue: 3,
        IntMaxCostCodeSearchLength: 254,
        IntMaxRecords: 100,
        IntMinFullCodeSearchLength: 0,
        IntNoneItemValue: -999999999,
        IntNotificationPollInterval: 60000,
        IntReportOutputFormatPDF: 4,
        IntReportProgressIntervalMilliseconds: 1000,
        IntSearchMaxLength: 200,
        IntShortProgressStatusIntervalMilliseconds: 500,
        IntUserIdMaxLengthValue: 50,
        IntWarningExceptionValue: 4,
        LngMaxFileSizeBytes: 1000000,
        ObjDataTypeMap: {
          IntAllowedCharacters: 8,
          IntAlpha: 2,
          IntAlphaNumeric: 1,
          IntAlphaNumericWithSymbols: 9,
          IntCustomFormat: 7,
          IntFullDate: 4,
          IntNumeric: 3,
          IntPartialDate: 5,
          IntTime: 6,
        },
        ObjInputMethodMap: {
          IntComboEdit: 3,
          IntComboList: 2,
          IntEdit: 1,
          IntEditMultiSelect: 4,
        },
        ObjMenuDownloadOptions: {
          ArrMenuItemFavorites: [],
          ArrMenuItems: [
            {
              ArrMenuItems: [
                {
                  ArrMenuItems: [],
                  BlnIsSeparator: false,
                  BlnPreventSelection: false,
                  StrMenuCommand: '8',
                  StrMenuText: 'HTML',
                  StrRootMenuCommand: 'Download',
                },
                {
                  ArrMenuItems: [],
                  BlnIsSeparator: false,
                  BlnPreventSelection: false,
                  StrMenuCommand: '4',
                  StrMenuText: 'PDF',
                  StrRootMenuCommand: 'Download',
                },
                {
                  ArrMenuItems: [],
                  BlnIsSeparator: false,
                  BlnPreventSelection: false,
                  StrMenuCommand: '128',
                  StrMenuText: 'OpenXML',
                  StrRootMenuCommand: 'Download',
                },
              ],
              BlnIsSeparator: false,
              BlnPreventSelection: false,
              StrMenuCommand: 'Download',
              StrMenuText: 'Download',
              StrRootMenuCommand: 'Download',
            },
          ],
        },
        ObjWebSocketMessageConfig: {
          StrCommandAbort: 'ABORT',
          StrCommandConnected: 'CONNECTED',
          StrCommandFailure: 'FAILURE',
          StrCommandGatherPrint: 'GATHER_PRINT',
          StrCommandLogOn: 'LOG_ON',
          StrCommandPasswordEntry: 'PASSWORD_ENTRY',
          StrCommandPing: 'PING',
          StrCommandPong: 'PONG',
          StrCommandRemovePrint: 'REMOVE_PRINT',
          StrCommandStartEmployeeVerification: 'START_EMPLOYEE_VERIFICATION',
          StrCommandStartEnrollment: 'START_ENROLLMENT',
          StrCommandStartNotifications: 'START_NOTIFICATIONS',
          StrCommandStartUserVerification: 'START_USER_VERIFICATION',
          StrCommandStartVerifyPassword: 'START_VERIFY_PASSWORD',
          StrCommandSuccess: 'SUCCESS',
          StrCommandUnknown: 'UNKNOWN',
          StrCommandWebClockOffline: 'WEBCLOCK_OFFLINE',
          StrCommandWebClockOnline: 'WEBCLOCK_ONLINE',
          StrErrorConnectingToWorkstationHubThroughWebSocket: 'Error connecting to workstation hub through web socket',
        },
        StrAccept: 'Accept',
        StrAccruals: 'Accruals',
        StrActive: 'Active',
        StrActiveOnly: 'Active only',
        StrActivePeriodStart: 'Starts After',
        StrActivePeriodStop: 'Stops After',
        StrAdd: 'Add',
        StrAdjustYourSettingsAndRefresh: 'Adjust the settings above and click "Update"',
        StrAll: 'All',
        StrAnd: 'and',
        StrApply: 'Apply',
        StrApproveAll: 'ApproveAll',
        StrAriaFlyoutButtonHelp: 'flyout, press enter to open, escape to close and tab keys to navigate',
        StrAscending: 'Ascending',
        StrAssign: 'Assign',
        StrAvailable: 'Available',
        StrBack: 'Back',
        StrBadgeNumber: 'Badge number',
        StrBreakType: 'Break type',
        StrBrowse: 'Browse',
        StrCalculator: 'Calculator',
        StrCall: 'Call',
        StrCancel: 'Cancel',
        StrCapsOnWarning: 'Caps Lock is on',
        StrChangeToHundredths: 'Change to Hundredths',
        StrChangeToMinutes: 'Change to Minutes',
        StrCharactersRemaining: 'characters remaining',
        StrClass: 'Classification',
        StrClear: 'Clear',
        StrClearAll: 'Clear All',
        StrClose: 'Close',
        StrCollapseAll: 'Collapse all',
        StrConfirmNavigateWithoutSaving: 'This feature has unsaved changes.||How do you want to continue?',
        StrConfirmNavigateWithoutSavingWithInvalidData:
          'This feature has unsaved changes and has invalid data.||How do you want to continue?',
        StrConfirmResumeSession: 'Your session has expired. Would you like to resume it?',
        StrContinue: 'Continue',
        StrDate: 'Date',
        StrDateIn: 'Date in',
        StrDateOut: 'Date out',
        StrDateOverMaxMessage: 'Date {0} is invalid. Date must be on or before {1}',
        StrDateUnderMinMessage: 'Date {0} is invalid. Date must be on or after {1}',
        StrDefault: 'Default',
        StrDelete: 'Delete',
        StrDepartment: 'Department',
        StrDescending: 'Descending',
        StrDescription: 'Description',
        StrDeselectAll: 'Deselect All',
        StrDeselectAllMessage: 'Deselect all {0} records',
        StrDetail: 'detail',
        StrDiscardChanges: 'Discard Changes',
        StrDisplayWeekendWarning: 'Some segments are hidden',
        StrDisplayWeekends: 'Display weekends',
        StrDownload: 'Download',
        StrEdit: 'Edit',
        StrElapsed: 'Elapsed',
        StrEmpty: 'Empty',
        StrEnterRequiredFields: 'Enter required field(s).',
        StrEnterValidAlpha: 'Enter valid alpha',
        StrEnterValidAlphaNumeric: 'Enter valid alpha numeric',
        StrEnterValidDate: 'Enter valid date',
        StrEnterValidDecimal: 'Enter valid decimal',
        StrEnterValidEmail: 'Enter valid email address',
        StrEnterValidExtension: 'Enter valid extension',
        StrEnterValidHostname: 'Enter valid hostname',
        StrEnterValidHours: 'Enter valid hours',
        StrEnterValidIpAddress: 'Enter valid IP address',
        StrEnterValidNumeric: 'Enter valid number',
        StrEnterValidPIN: 'Enter valid PIN',
        StrEnterValidPhone: 'Enter valid phone number',
        StrEnterValidSMS: 'Enter valid SMS address',
        StrEnterValidSSN: 'Enter valid Social Security Number',
        StrEnterValidTime: 'Enter valid time',
        StrEnterValidZip: 'Enter valid zip code',
        StrExceedsMaximumSize: 'File exceeds maximum size of 1 MB',
        StrException: 'Exception',
        StrExceptionTypeHeaderKey: 'EXCEPTION_TYPE',
        StrExceptions: 'Exceptions',
        StrExit: 'Close',
        StrExpandAll: 'Expand all',
        StrExportCode: 'Export code',
        StrFeedback: 'Feedback',
        StrFilter: 'Filter',
        StrFilters: 'Filters',
        StrFinish: 'Finish',
        StrFirstName: 'First name',
        StrGroup: 'Group',
        StrHelp: 'Help',
        StrHelpUrl: 'https://timeclockplus.force.com/TCPSupport/s/',
        StrHiddenUnavailableSegmentsWarning: 'Some unavailable segments are hidden',
        StrHireDate: 'Hire date',
        StrHome: 'Home',
        StrHours: 'Hours',
        StrHundredths: 'Hundredths',
        StrId: 'ID',
        StrIncompatibleBrowserError: 'For best experience please use a supported browser: IE 10+, Chrome, FireFox',
        StrIndividual: 'Individual',
        StrInvalidSelection: 'Invalid selection',
        StrLastName: 'Last name',
        StrLeave: 'Leave',
        StrLoad: 'Load',
        StrLoadAllData: 'Load all data',
        StrLocation: 'Location',
        StrLocationFilter: 'Location Filter',
        StrLogOff: 'Log Off',
        StrLogoTitle: 'Logo',
        StrMainNavigation: 'Main navigation',
        StrManage: 'Manage',
        StrManager: 'Manager',
        StrMap: 'Map',
        StrMessage: 'Message',
        StrMin: 'min',
        StrMinutes: 'Minutes',
        StrMultiSelectNewValueErrorMessage: 'Please enter valid unique entry without containing semicolon',
        StrMyOptions: 'My Options',
        StrName: 'Name',
        StrNavigatePeriod: 'Navigate Period',
        StrNavigationWarning:
          'A task is currently running. Navigating away from this page may result in a loss of data. Are you sure you wish to continue?',
        StrNewEntry: 'New Entry',
        StrNext: 'Next',
        StrNextPeriod: 'Next period',
        StrNextWeek: 'Next Week',
        StrNo: 'No',
        StrNoDataText: 'No records found',
        StrNoRecordSelectedMessage: 'Please select an item to continue',
        StrNone: 'None',
        StrNoneItem: '<< NONE >>',
        StrNote: 'Note',
        StrOT1: 'OT1',
        StrOT2: 'OT2',
        StrOffline: 'Offline',
        StrOk: 'Ok',
        StrOpensNewModal: ' Opens new dialog',
        StrOpensNewWindow: ' opens new window',
        StrOperationSuccessful: 'Operation successful',
        StrOptional: 'Optional',
        StrOptions: 'Options',
        StrOrder: 'Order',
        StrOverflow: 'Overflow',
        StrOverridden: 'Overridden',
        StrOverrideRoleSettings: 'Override role settings',
        StrOvertime: 'Overtime',
        StrOvertime1: 'Overtime 1',
        StrOvertime2: 'Overtime 2',
        StrPIN: 'PIN',
        StrPageLayout: 'Page Layout',
        StrPageNumber: 'Page {0}',
        StrPageOf: 'Page {0} of {1}',
        StrPassword: 'Password',
        StrPasteWillResultInInvalidLength: 'Paste will result in invalid length',
        StrPeriodLabel: 'Period',
        StrPeriodStartDateLabel: 'Start date',
        StrPeriodStopDateLabel: 'Stop date',
        StrPrev: 'Prev',
        StrPrevWeek: 'Prev Week',
        StrPreview: 'Preview',
        StrPreviousPeriod: 'Previous Period',
        StrPrint: 'Print',
        StrProcess: 'Process',
        StrProcessIndicatorTitle: 'Processing',
        StrRate: 'Rate',
        StrRefresh: 'Refresh',
        StrRegular: 'Regular',
        StrReject: 'Reject',
        StrRemaining: 'Remaining',
        StrRemoveAll: 'Remove All',
        StrReportProgressMessage: 'Generating report...',
        StrRequiresApproval: 'Requires Approval',
        StrResources: 'Resources',
        StrResumeTutorial: 'Resume tutorial',
        StrRole: 'Role',
        StrRoleDescription: 'Role Description',
        StrSMS: 'SMS',
        StrSave: 'Save',
        StrSaveAs: 'Save as',
        StrSchedule: 'Schedule',
        StrSearch: 'Search',
        StrSegmentFilter: 'Segment Filter',
        StrSegmentLength: 'Segment Length',
        StrSelect: 'Select',
        StrSelectAll: 'Select All',
        StrSelectAllMessage: 'Select all {0} records',
        StrSelectEntity: 'Select Item',
        StrSelectedEntityMessage: 'Selected {0} records',
        StrSelectedItem: 'Selected Item :',
        StrSeniorityDate: 'Seniority Date',
        StrSessionTimeoutWarningMessage: 'Session will timeout in {0} seconds',
        StrSettings: 'Settings',
        StrShowDetails: 'Show Details',
        StrShowExceptions: 'Show Exceptions',
        StrShowingOf: 'Showing {0} records of {1}',
        StrSort: 'Sort',
        StrSortByDirection: 'Sort By Direction',
        StrSortByField: 'Sort by: {0}',
        StrSortByOption: 'Sort By Option',
        StrStartGreaterThanEnd: 'The start date should be before the end date.',
        StrStartTime: 'Start time',
        StrStatus: 'Status',
        StrStayActive: 'Stay Active',
        StrStopTime: 'Stop time',
        StrTemplates: 'Templates',
        StrTextExceedsCharacterLimit: "Character limit can't exceed 200",
        StrTextExceedsMaxLength: 'The text exceeds the maximum number of allowed characters.',
        StrTheCurrentWeek: 'the current week ({0})',
        StrTime: 'Time',
        StrTimeIn: 'Time in',
        StrTimeOut: 'Time out',
        StrTimesheet: 'Time sheet',
        StrTimesheetEntry: 'Time Sheet Entry',
        StrTo: 'to',
        StrTop: 'Top',
        StrTotal: 'Total',
        StrTrackedFields: 'Tracked Fields',
        StrType: 'Type',
        StrUnassign: 'Unassign',
        StrUnavailable: 'Unavailable',
        StrUnexpectedErrorMessage:
          '{0}||An unexpected error has occurred.||If this message persists please try clearing your application cache and refreshing your browser.',
        StrUpdate: 'Update',
        StrUseArrowKeysHelp: 'Use arrow keys to navigate',
        StrVersionClientLabel: 'Client: ',
        StrVersionRevisionLabel: 'Revision: ',
        StrVersionServerLabel: 'Server: ',
        StrView: 'View',
        StrViewLoaded: 'view loaded',
        StrYes: 'Yes',
      },
      ObjApprovalStatusConfig: {
        ObjIntStringItemApproved: {
          IntKey: 2,
          StrHelp: '',
          StrId: '',
          StrText: 'Approved',
        },
        ObjIntStringItemDenied: {
          IntKey: 3,
          StrHelp: '',
          StrId: '',
          StrText: 'Denied',
        },
        ObjIntStringItemPending: {
          IntKey: 1,
          StrHelp: '',
          StrId: '',
          StrText: 'Pending',
        },
      },
      ObjDateTimeFormatConfig: {
        BlnFormatHoursAsDecimals: false,
        IntHourFormatPrecision: 2,
        StrDateFormat: 'M/d/yyyy',
        _StrTimeFormat: 'hh:mm tt',
      },
      ObjManagerStartInConfig: {
        IntStartInAttendanceMonitor: 2,
        IntStartInDailyOverallSchedule: 10,
        IntStartInDashboard: 0,
        IntStartInEmployeeStatus: 1,
        IntStartInGlobalScheduler: 11,
        IntStartInGroupHours: 8,
        IntStartInIndividualSchedule: 12,
        IntStartInManageEmployee: 6,
        IntStartInManageHours: 4,
        IntStartInManageJobCode: 7,
        IntStartInManageRequests: 5,
        IntStartInManagerReports: 3,
        IntStartInRecurringSchedules: 13,
        IntStartInScheduleTemplates: 14,
        IntStartInSchedulerReports: 9,
        IntStartInStaffingRequirements: 15,
        IntStartInWeeklyOverallSchedule: 16,
      },
      StrAddressNotFound: 'Address Not Found',
      StrBiometricVerificationLabel: 'Biometric Verification',
      StrCT: 'Comp Time',
      StrClickHere: 'click here',
      StrCompanyDisplayValue: 'Webclock',
      StrCompanyNamespace: '',
      StrCompanyTimestamp: '2021-05-14 21:51:34',
      StrCostCode: 'Cost Code',
      StrCostCodeFilter: 'Cost Code Filter',
      StrCostCodeGroup: 'Cost Code Group',
      StrCostCodes: 'Cost Codes',
      StrCover: 'Substitute',
      StrCoverFor: 'Substitute for',
      StrCoveredEmployeeFilter: 'Covered Employee Filter',
      StrCurrencySymbol: '',
      StrCurrentWeekTimestamp: '2021-05-02 00:00:00',
      StrDatePickerLocale: '',
      StrDefaultCostCode: 'Default Cost Code',
      StrDefaultJobCode: 'Default Job Code',
      StrDemand: 'Demand',
      StrEmployee: 'Employee',
      StrEmployeeFilter: 'Employee Filter',
      StrEmployeeId: 'Employee ID',
      StrEmployeeTypeFilter: 'Employee Type Filter',
      StrEmployees: 'Employees',
      StrExceptionFilter: 'Exception Filter',
      StrFormattedCurrentWeekDate: '05/02/2021',
      StrInvalidCostCode: 'Invalid cost code',
      StrJobClassFilter: 'Job Class Filter',
      StrJobCode: 'Job Code',
      StrJobCodeFilter: 'Job Code Filter',
      StrJobCodeGroup: 'Job Code Group',
      StrJobCodes: 'Job Codes',
      StrLaborCode: 'Labor Code',
      StrLaborCodes: 'Labor Codes',
      StrLaborStandard: 'Labor Standard',
      StrLaborStandardFilter: 'Labor Standard Filter',
      StrLeaveCalendarFilter: 'Leave Calendar Filter',
      StrMasterSchedule: 'Master Schedule',
      StrMasterScheduleFilter: 'Master Schedule Filter',
      StrMasterShift: 'Master Shift',
      StrMasterShiftFilter: 'Master Shift Filter',
      StrMonthDayFormat: 'MM/dd',
      StrPrimarySortKey: 'Primary Sort Key',
      StrReleaseNotes: 'Release Notes',
      StrResourceRequirements: 'Resource Requirements',
      StrScheduleGroup: 'Schedule Group',
      StrScheduleGroupSentenceCase: 'Schedule group',
      StrSecondarySortKey: 'Secondary Sort Key',
      StrShiftBidStatus: 'Shift Bid Status',
      StrSortKeys: 'Sort Key Settings',
      StrSubstituteEmployeeFilter: 'Substitute Employee Filter',
      StrTimeRangeFilter: 'Time Range Filter',
      StrTrack1: 'Track1',
      StrTrack1MaxValue: '9999999',
      StrTrack2: 'Track2',
      StrTrack2MaxValue: '9999999.9',
      StrTrack3: 'Track3',
      StrTrack3MaxValue: '9999999.99',
      _ArrDatePeriods: [
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-05-14',
          IntPeriod: 18,
          StrDescription: 'Manual',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-15',
          DatStartDate: '2021-05-02',
          IntPeriod: 33,
          StrDescription: 'Open Weeks',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-08',
          DatStartDate: '2021-05-02',
          IntPeriod: 3,
          StrDescription: 'TimeClock Week',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-15',
          DatStartDate: '2021-05-09',
          IntPeriod: 7,
          StrDescription: 'This Week',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-15',
          DatStartDate: '2021-05-09',
          IntPeriod: 12,
          StrDescription: 'This Period',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-05-14',
          IntPeriod: 1,
          StrDescription: 'Today',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-05-02',
          IntPeriod: 17,
          StrDescription: 'TimeClock Week To Date',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-13',
          DatStartDate: '2021-05-13',
          IntPeriod: 2,
          StrDescription: 'Yesterday',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-08',
          DatStartDate: '2021-05-02',
          IntPeriod: 9,
          StrDescription: 'Last Week',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-04-30',
          DatStartDate: '2021-04-01',
          IntPeriod: 6,
          StrDescription: 'Last Month',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2020-12-31',
          DatStartDate: '2020-01-01',
          IntPeriod: 16,
          StrDescription: 'Last Year',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-05-09',
          IntPeriod: 10,
          StrDescription: 'Week To Date',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-05-01',
          IntPeriod: 4,
          StrDescription: 'Month To Date',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-01-01',
          IntPeriod: 5,
          StrDescription: 'Year To Date',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-08',
          DatStartDate: '2021-05-02',
          IntPeriod: 11,
          StrDescription: 'Last Period',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-04-14',
          IntPeriod: 13,
          StrDescription: 'Last 30 Days',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-03-15',
          IntPeriod: 14,
          StrDescription: 'Last 60 Days',
        },
        {
          BlnIsHistory: true,
          DatEndDate: '2021-05-14',
          DatStartDate: '2021-02-13',
          IntPeriod: 15,
          StrDescription: 'Last 90 Days',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-22',
          DatStartDate: '2021-05-16',
          IntPeriod: 8,
          StrDescription: 'Next Week',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-05-22',
          DatStartDate: '2021-05-16',
          IntPeriod: 32,
          StrDescription: 'Next Period',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-06-12',
          DatStartDate: '2021-05-14',
          IntPeriod: 26,
          StrDescription: 'Next 30 Days',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-07-12',
          DatStartDate: '2021-05-14',
          IntPeriod: 27,
          StrDescription: 'Next 60 Days',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-08-11',
          DatStartDate: '2021-05-14',
          IntPeriod: 28,
          StrDescription: 'Next 90 Days',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2021-11-13',
          DatStartDate: '2021-05-14',
          IntPeriod: 29,
          StrDescription: 'Next 6 Months',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2022-02-13',
          DatStartDate: '2021-05-14',
          IntPeriod: 30,
          StrDescription: 'Next 9 Months',
        },
        {
          BlnIsHistory: false,
          DatEndDate: '2022-05-13',
          DatStartDate: '2021-05-14',
          IntPeriod: 31,
          StrDescription: 'Next 12 Months',
        },
      ],
      _StrTickerTimeFormat: 'hh:mm:ss tt',
    } as CompanyConfig,
    CompanyConfigImpl,
  );
}
